[general]
name = "tinygrad-rms"
version = 1
backends = ["cuda"]


[general.hub]
repo-id = "kernels-community/tinygrad-rms"

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.tinygrad_rms]
backend = "cuda"
depends = ["torch"]
src = ["tinygrad_rms_cuda/tinygrad_rms.cu"]
