[general]
name = "rotary"
version = 1
backends = [
    "cuda",
    "xpu",
]


[general.hub]
repo-id = "kernels-community/rotary"

[torch]
src = ["torch-ext/torch_binding.cpp"]

[kernel.rotary_xpu]
backend = "xpu"
depends = ["torch"]
src = [
    "rotary-xpu/rotary_xpu.cpp",
    "rotary-xpu/rotary_xpu.hpp",
]

[kernel.activation]
backend = "cuda"
depends = ["torch"]
src = ["rotary/rotary_cuda.cu"]
