[general]
name = "deformable-detr"
license = "Apache-2.0"
version = 1
backends = ["cuda"]

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.activation]
backend = "cuda"
depends = ["torch"]
include = ["."]
src = [
    "deformable_detr/ms_deform_attn_cuda.cu",
    "deformable_detr/ms_deform_im2col_cuda.cuh",
    "deformable_detr/ms_deform_attn_cuda.cuh",
    "deformable_detr/ms_deform_attn_cuda.h",
]
