[general]
name = "activation"
license = "Apache-2.0"
version = 1
backends = ["cuda", "metal"]

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.activation]
backend = "cuda"
depends = ["torch"]
src = [
    "activation/activation_kernels.cu",
    "activation/cuda_compat.h",
    "activation/dispatch_utils.h",
]

[kernel.activation_metal]
backend = "metal"
depends = ["torch"]
src = [
    "activation_metal/activation.mm",
    "activation_metal/activation.metal",
]
